### ISSUE TITLE
Why are there inconsistencies with "req" and "res"?

### ISSUE THREAD

**Issue by atom-morgan** [Microsoft/TypeScriptSamples#115]
In [index.ts](https://github.com/Microsoft/TypeScriptSamples/blob/master/imageboard/routes/index.ts#L4) the `req` and `res` objects have their type specified.

```
export function index(req: express.Request, res: express.Response) { };
```

But in [app.ts](https://github.com/Microsoft/TypeScriptSamples/blob/master/imageboard/app.ts#L64) they're missing.

``
app.get('/user/:userid', (req, res) => { };
``

I'm in the process of converting an ES6 Express API to TypeScript and was wondering if there is a reason for this.

**Comment by DanielRosenwasser** [comment]
Hey @atom-morgan, in some places, the types of each parameter can be inferred.

In the second case, they can be, because we know the type from `app.get`, but in the first, it's harder to tell what consumers (if any) might use the `index` function, and make inferences from that. So without type annotations, TypeScript would've taken the most lenient route and picked `any`.

If you'd like to know the places where TypeScript would've picked any out, you can use the `--noImplicitAny` flag, where the compiler will flag locations where it couldn't pick a better type.

**Comment by atom-morgan** [comment]
I think that makes sense. Thanks for your response!
